export const GET_ALL_DEVICES_RQUEQUEST = 'GET_ALL_DEVICES_RQUEQUEST';
export const GET_ALL_DEVICES_SUCCESS = 'GET_ALL_DEVICES_SUCCESS';
export const GET_ALL_DEVICES_FAIL = 'GET_ALL_DEVICES_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
